#!/bin/bash

[ -f ~/.xprofile ] && . ~/.xprofile

gnome-keyring-daemon

$HOME/scr/screen2.sh

{
    while $(pidof budwm); do
        sleep 0.1
    done

    sleep 0.1
    xrdb ~/.Xresources
    xrandr --dpi 144
} &

# exec surf -f -k google.com
exec budwm
