#!/bin/bash
exec bemenu --fn "CascadiaMonoPL Nerd Font Mono 14" \
    --tb '#0f090c' --tf '#d9cfd3' \
    --fb '#0f090c' --ff '#d9cfd3' \
    --cb '#d9cfd3' --cf '#36001B' \
    --nb '#0f090c' --nf '#666666' \
    --hb '#36001B' --hf '#d9cfd3' \
    --fbb '#36001B' --fbf '#d9cfd3' \
    --sb '#36001B' --sf '#d9cfd3' \
    --ab '#0f090c' --af '#666666' \
    --scb '#36001B' --scf '#d9cfd3' \
    --bdr '#36001B' \
    --hp 10 --list 15 \
    -B 2 --fixed-height --counter always
