#!/bin/bash
exec bemenu-run --fn "CascadiaMonoPL Nerd Font Mono 14" \
    --tb '#f7c54b' --tf '#000000' \
    --fb '#f7c54b' --ff '#000000' \
    --cb '#000000' --cf '#ffffff' \
    --nb '#624200' --nf '#f7c54b' \
    --hb '#ffffff' --hf '#000000' \
    --fbb '#ffffff' --fbf '#000000' \
    --sb '#ffffff' --sf '#000000' \
    --ab '#624200' --af '#f7c54b' \
    --scb '#ffffff' --scf '#000000' \
    --bdr '#ffffff' \
    --hp 10 --list 15 \
    -B 2 --fixed-height --counter always
